import { renderPdf } from './pdf.js';
import type { Line } from './pdf.js';
import type { TailoredResume } from './tailor.js';
import type { CandidateProfile } from '../plan/types.js';

/**
 * The tailored résumé as a document an employer can actually receive.
 *
 * Until this existed, tailoring was advice. `compilePlan` resolved every file
 * field to `profile.resumePath` — the same static PDF for every application —
 * so the app would work out which bullets fit a posting, show the candidate,
 * and then attach the file they uploaded months ago. The selection never left
 * the screen.
 *
 * Two rules carry over from docs/DECISIONS.md #1 and are load-bearing here:
 *
 *   Every line of prose in this document is the candidate's own, character for
 *   character. Nothing is rewritten, summarised or generated. The renderer
 *   composes headings out of profile *facts* — a name, a title, a date range —
 *   and otherwise only chooses which of the candidate's sentences to print.
 *
 *   Dropped bullets are dropped, not softened. A bullet that did not earn its
 *   place is absent from the file, and `tailored.dropped` still lists it on
 *   screen so the omission is visible rather than silent.
 *
 * There is deliberately no app name, watermark or "generated by" line. It is
 * the candidate's résumé, submitted under their name.
 */

const H1 = 17;
const H2 = 10.5;
const BODY = 9.8;
const SMALL = 8.8;

/** "2023-06" → "Jun 2023". Anything unparseable is passed through verbatim. */
function month(raw: string | undefined): string {
  if (!raw) return '';
  const m = /^(\d{4})-(\d{1,2})$/.exec(raw.trim());
  if (!m) return raw.trim();
  const names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const i = Number(m[2]) - 1;
  return i >= 0 && i < 12 ? `${names[i]} ${m[1]}` : raw.trim();
}

function dateRange(start: string | undefined, end: string | undefined): string {
  const from = month(start);
  // An absent end date means current, which is a claim worth stating plainly.
  const to = end && end.trim() ? month(end) : 'Present';
  if (!from) return to === 'Present' ? '' : to;
  return `${from} – ${to}`;
}

function contactLine(p: CandidateProfile): string {
  return [
    p.email, p.phone,
    p.location ?? [p.city, p.state, p.country].filter(Boolean).join(', '),
  ].map((s) => (s ?? '').trim()).filter((s) => s.length > 0).join('  ·  ');
}

function linksLine(p: CandidateProfile): string {
  return [p.linkedin, p.github, p.website]
    .map((s) => (s ?? '').trim())
    .filter((s) => s.length > 0)
    // The scheme is noise on paper and the link still resolves without it.
    .map((s) => s.replace(/^https?:\/\//, ''))
    .join('  ·  ');
}

/**
 * Build the line list. Exported so the layout can be asserted on as data,
 * rather than by reading bytes back out of a PDF.
 */
export function resumeLines(tailored: TailoredResume, profile: CandidateProfile): Line[] {
  const lines: Line[] = [];
  const name = `${profile.firstName ?? ''} ${profile.lastName ?? ''}`.trim();

  if (name) lines.push({ text: name, size: H1, face: 'bold' });
  if (profile.currentTitle) {
    lines.push({ text: profile.currentTitle, size: H2, face: 'regular', spaceBefore: 2 });
  }
  const contact = contactLine(profile);
  if (contact) lines.push({ text: contact, size: SMALL, face: 'regular', spaceBefore: 5 });
  const links = linksLine(profile);
  if (links) lines.push({ text: links, size: SMALL, face: 'regular', spaceBefore: 1 });

  const skills = (profile.skills ?? []).filter((s) => String(s).trim().length > 0);
  if (skills.length > 0) {
    lines.push({ text: 'SKILLS', size: SMALL, face: 'bold', spaceBefore: 16 });
    lines.push({ text: skills.join(' · '), size: BODY, face: 'regular', spaceBefore: 4 });
  }

  const roles = tailored.roles.filter((r) => r.kept.length > 0);
  if (roles.length > 0) {
    lines.push({ text: 'EXPERIENCE', size: SMALL, face: 'bold', spaceBefore: 16 });
    for (const role of roles) {
      const heading = [role.title, role.company].filter(Boolean).join(', ');
      lines.push({ text: heading, size: H2, face: 'bold', spaceBefore: 11 });

      const meta = [dateRange(role.start, role.end ?? undefined), role.location ?? '']
        .map((s) => s.trim()).filter((s) => s.length > 0).join('  ·  ');
      if (meta) lines.push({ text: meta, size: SMALL, face: 'regular', spaceBefore: 2 });

      for (const bullet of role.kept) {
        // The hanging indent is why the marker is drawn as its own line rather
        // than prefixed onto the text: a wrapped bullet lines up under the
        // first word, not under the dash.
        lines.push({ text: `-  ${bullet.text}`, size: BODY, face: 'regular', spaceBefore: 4, indent: 10 });
      }
    }
  }

  return lines;
}

/** The tailored résumé as PDF bytes. */
export function renderResume(tailored: TailoredResume, profile: CandidateProfile): Buffer {
  return renderPdf(resumeLines(tailored, profile));
}

/**
 * A filename an employer will read in a list of hundreds.
 *
 * Name first because that is what a recruiter scans for, then the company, so
 * two applications from the same candidate do not collide in a downloads
 * folder. Restricted to characters every filesystem and Content-Disposition
 * header agrees on.
 */
export function resumeFilename(profile: CandidateProfile, company: string): string {
  const clean = (s: string): string => s
    .normalize('NFKD')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
  const who = clean(`${profile.firstName ?? ''} ${profile.lastName ?? ''}`) || 'resume';
  const where = clean(company);
  return `${[who, where].filter((s) => s.length > 0).join('-')}.pdf`;
}
